server:
  port: 8082
  tomcat:
    threads:
      max: 25
    accept-count: 25
    max-connections: 100

feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true

hm:
  db:
    database: hm-cart

  swagger:
    package: com.heima.cart.controller

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8091
      http-method-specify: true

seata:
  enabled: true
  application-id: your-app-id
  tx-service-group: your-tx-group
  service:
    vgroup-mapping:
      your-tx-group: default
    grouplist:
      default: 127.0.0.1:8091
  enable-auto-data-source-proxy: true
